# Generated by Django 4.2.1 on 2023-05-26 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msg',
            options={'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='msg',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 26, 11, 32, 47, 267365)),
        ),
    ]
